name: Build and upload

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        run: pipx run build --sdist

      - name: Validate
        run: |
          pip install twine
          twine check dist/*

      - name: Install and test
        run: |
          pip install --find-links=dist pytetwild[dev]
          pytest -x

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz
          name: pytetwild-sdist
